name: Publish To Wordpress

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get install -y subversion
          svn checkout --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}} ${{secrets.SVN_URL}} wp-plugin --depth empty
          svn add --force wp-plugin/*
          svn update wp-plugin/* --accept mine-full
          svn resolve wp-plugin --accept working -R
          svn commit wp-plugin -m "${{github.event.release.name}}: ${{github.event.release.body}}" --username=${{secrets.SVN_USER}} --password=${{secrets.SVN_PASS}}
